# Generated by Django 3.2.20 on 2023-10-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
