# Generated by Django 3.2.20 on 2023-10-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks'),
        ),
    ]
