# Generated by Django 3.2.20 on 2023-10-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20231018_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
